### ISSUE TITLE
Pass custom variables from pelicanconf.py

### ISSUE THREAD

**Issue by Mte90** [pelican-plugins/jinja2content#6]
So as explained in the readme in those templates that integrate jinja they are not available as this code is executed before to arrive to pelican.

Maybe it is possible to share some variables from pelican anyway?
I see that some variables are shared https://github.com/pelican-plugins/jinja2content/blob/main/pelican/plugins/jinja2content/jinja2content.py#L25 so they need to pass to jinja, maybe it is possible to create `VARIABLES_FOR_JINJA` or something better.

The second step is to understand if it is possible to access to stuff like `articles` in a way that is possible to do a loop of them in the home page, but I am not sure if a template to embed in the pages will achieve the same effect.

**Comment by JonathanMair** [comment]
+1  🙏 

This would be really useful functionality because it would make it possible to set up some specific custom quasi-dynamic content in pages or posts rather than messing with the templates of the theme and thereby making it necessary to keep the customisation synced with theme updates. 

For example, in my case I'd like to make a single category page for *one* of my categories. I could probably do that by modifying the theme, but I'd like to do it in a page that will provide a summary of the category, perhaps some other custom content, and a list of articles in the category that will be generated automatically when I generate the site. I had assumed jinja2content would allow access to the relevant variables (e.g. `articles`) from within pages—I understand why it's implemented as it is but perhaps there's a workaround.

**Comment by justinmayer** [comment]
@micahjsmith / @daturkel: Any thoughts about this idea for the Jinja2Content plugin?

**Comment by JonathanMair** [comment]
PS: I've found the way in which what I wanted should be done now—using the THEME_TEMPLATES_OVERRIDE in the pelican settings file. That allows for using modified theme templates without messing up the theme.

It works in my case (mainly because I'm trying to replace pages that would be among a few generated from a given theme template and I'm happy for all of the pages generated from that template to be the same. But clearly it wouldn't be convenient for all cases.

**Comment by micahjsmith** [comment]
@justinmayer it would be great to have this feature but it would be pretty tricky to fully implement. pelican is doing a ton of stuff at generation time, running a bunch of signals, etc. so the risk of making things like `articles` available is that pre-generation time this variable could not be computed in the right away since it's outside of pelican's managed lifecycle. on the other hand, a much more minimal implementation like `JINJA2CONTENT_VARIABLES` setting with user-defined variables is easy to implement. implementation would be similar to https://github.com/pelican-plugins/jinja2content/blob/main/pelican/plugins/jinja2content/jinja2content.py#L43-L44. note that you can already use `JINJA_GLOBALS` to inject custom variables to the jinja2content rendering, though these globals would also be available for normal pelican rendering.

disclaimer: I no longer am developing on pelican, just making periodic updates to my personal blog's contents, so I no longer remember the intricacies as well

**Comment by justinmayer** [comment]
@micahjsmith: Many thanks for the thoughtful reply. Much appreciated! 😁

@Mte90: It seems like `JINJA_GLOBALS` might provide the solution you are looking for, without having to make any changes to this plugin. What do you think?

**Comment by Mte90** [comment]
I am not using anymore Pelican (I was experimenting) and switched to another solution, so I am not sure if I am the best in this discussion now.

**Comment by justinmayer** [comment]
@Mte90: No worries, Daniele. If you ever find yourself in Trentino, let me know and we can chat over a glass of Nosiola or Teroldego. 🍷
